support/config/routes.rb
Rails.application.routes.draw do

  resources :requests

end

support/app/models/request.rb
class Request < ActiveRecord::Base
end

support/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

support/app/controllers/requests_controller.rb
class RequestsController < ApplicationController

  def new
    @request = Request.new
  end

  def create
    request_params  = params.require(:request).permit(:name, :email, :department, :message, :status)
    @request        = Request.new request_params
    if @request.save
      redirect_to requests_path
    else
      render :new
    end
  end

  def show
    @request = Request.find params[:id]
  end

  def index
    @request = Request.order(id: :desc)
  end

  def edit
    @request = Request.find params[:id]
  end

  def update
    @request = Request.find params[:id]
    request_params  = params.require(:request).permit(:name, :email, :department, :message, :status)
    @request.update request_params
    redirect_to requests_path
  end

  def destroy
    @request = Request.find params[:id]
    @request.destroy
    redirect_to requests_path
  end

end

support/app/helpers/application_helper.rb
module ApplicationHelper
end

support/app/helpers/requests_helper.rb
module RequestsHelper
end

support/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Support</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

support/app/views/requests/edit.html.erb
<h4>Supporter</h4>
<hr>
<%= form_for @request do |f| %>
  <div>
    <%= f.label "Name *" %>
    <%= f.text_field :name %>
  </div>
  <div>
    <%= f.label "Email *" %>
    <%= f.text_area :email %>
  </div>
  <div>
    Deparment
    <%= f.radio_button(:department, "Sales") %>
    <%= f.label(:sales, "Sales") %>
    <%= f.radio_button(:department, "Marketing") %>
    <%= f.label(:marketing, "Marketing") %>
    <%= f.radio_button(:department, "Technical") %>
    <%= f.label(:marketing, "Technical") %>
  </div>
  <div>
    <%= f.label :message %>
    <%= f.text_area :message %>
  </div>
  <div>
    <%= f.hidden_field :status, value: "Not Done" %>
  </div>
  <%= f.submit value="Save"%>
<% end %>

support/app/views/requests/index.html.erb
<h1>Support Requests</h1>

<div class="Table">
    <div class="Heading">
        <div class="Cell">
            <p>Name</p>
        </div>
        <div class="Cell">
            <p>Email</p>
        </div>
        <div class="Cell">
            <p>Deparment</p>
        </div>
        <div class="Cell">
            <p>Message</p>
        </div>
        <div class="Cell">
            <p>Actions</p>
        </div>
    </div>
    <% @request.each do |request| %>
    <div class="Row">
        <div class="Cell">
            <p><%= request.name %></p>
        </div>
        <div class="Cell">
            <p><%= request.email %></p>
        </div>
        <div class="Cell">
            <p><%= request.department %></p>
        </div>
        <div class="Cell">
            <p><%= request.message %></p>
        </div>
        <div class="Cell">
            <p><%= link_to "Edit", edit_request_path(request) %>
               <%= link_to "Delete", request_path(request),
                                    method: :delete,
                                    data:   {confirm: "Are you sure?"} %></p>
        </div>
    </div>
    <% end %>
</div>

support/app/views/requests/new.html.erb
<h4>Supporter</h4>
<hr>
<%= form_for @request do |f| %>
  <div>
    <%= f.label "Name *" %>
    <%= f.text_field :name %>
  </div>
  <div>
    <%= f.label "Email *" %>
    <%= f.text_area :email %>
  </div>
  <div>
    Deparment
    <%= f.radio_button(:department, "Sales") %>
    <%= f.label(:sales, "Sales") %>
    <%= f.radio_button(:department, "Marketing") %>
    <%= f.label(:marketing, "Marketing") %>
    <%= f.radio_button(:department, "Technical") %>
    <%= f.label(:marketing, "Technical") %>
  </div>
  <div>
    <%= f.label :message %>
    <%= f.text_area :message %>
  </div>
  <div>
    <%= f.hidden_field :status, value: "Not Done" %>
  </div>
  <%= f.submit value="Save"%>
<% end %>

support/app/views/requests/show.html.erb
<h4>Supporter</h4>
<hr>
<p>Name: <%= @request.name %><p>
<p>Email: <%= @request.email %><p>
<p>Department: <%= @request.department %><p>
<p>Message: <%= @request.message %><p>
<p>Status: <%= @request.status %><p>

<%= link_to "Edit", edit_request_path(@request) %>
<%= link_to "Delete", request_path(@request),
                      method: :delete,
                      data:   {confirm: "Are you sure?"} %>